CC=gcc
INCLUDES=./include/
SOURCES=./source/site.c ./source/pchave.c ./source/lista_pchave.c ./source/lista_site.c ./source/utils.c ./source/prompt_usuario.c
BINARY=./test
PROG=./main.c

all:
	$(CC) -g -o $(BINARY) $(PROG) $(SOURCES) -I$(INCLUDES) 

run:
	$(BINARY)


